// This code was generated by the BehaveN tool.

using BehaveN;
using NUnit.Framework;
using System.Reflection;

namespace BehaveN.Examples
{
    [TestFixture]
    public partial class CalculatorScenarios
    {
        private FeatureFile ff = new FeatureFile();

        [TestFixtureSetUp]
        public void LoadScenarios()
        {
            ff.StepDefinitions.UseStepDefinitionsFromAssembly(GetType().Assembly);
            ff.LoadEmbeddedResource(GetType().Assembly, "CalculatorScenarios.txt");
        }

        [TestFixtureTearDown]
        public void ReportUndefinedSteps()
        {
            ff.ReportUndefinedSteps();
        }

        [Test]
        public void Adding_two_numbers()
        {
            ff.Scenarios["Adding two numbers"].Verify();
        }

        [Test]
        public void Subtracting_two_numbers()
        {
            ff.Scenarios["Subtracting two numbers"].Verify();
        }

        [Test]
        public void Dividing_two_numbers()
        {
            ff.Scenarios["Dividing two numbers"].Verify();
        }
    }
}
