// This code was generated by the BehaveN tool.

using BehaveN;
using NUnit.Framework;

namespace BehaveN.Examples
{
    [TestFixture]
    public class CalculatorScenarios
    {
        private FeatureFile ff;

        [TestFixtureSetUp]
        public void LoadScenarios()
        {
            ff = new FeatureFile();
            ff.StepDefinitions.UseStepDefinitionsFromAssembly(GetType().Assembly);
            ff.LoadEmbeddedResource(GetType().Assembly, "CalculatorScenarios.txt");
        }

        [TestFixtureTearDown]
        public void ReportUndefinedSteps()
        {
            ff.ReportUndefinedSteps();
        }

        [Test]
        public void Adding_two_numbers()
        {
            Scenario s = ff.Scenarios["Adding two numbers"];
            s.Verify();
            s.Report();
            if (!s.Passed) Assert.Fail();
        }

        [Test]
        public void Subtracting_two_numbers()
        {
            Scenario s = ff.Scenarios["Subtracting two numbers"];
            s.Verify();
            s.Report();
            if (!s.Passed) Assert.Fail();
        }

        [Test]
        public void Dividing_two_numbers()
        {
            Scenario s = ff.Scenarios["Dividing two numbers"];
            s.Verify();
            s.Report();
            if (!s.Passed) Assert.Fail();
        }
    }
}
