// This code was generated by the BehaveN tool.

using BehaveN;
using NUnit.Framework;
using System.Reflection;

namespace BehaveN.Examples
{
    [TestFixture]
    public partial class CalculatorScenarios
    {
        private Feature _feature = new Feature();

        [TestFixtureSetUp]
        public void LoadScenarios()
        {
            _feature.StepDefinitions.UseStepDefinitionsFromAssembly(GetType().Assembly);
            new PlainTextReader().ReadTo(Read.EmbeddedResource(GetType().Assembly, "CalculatorScenarios.txt"), _feature);
        }

        [TestFixtureTearDown]
        public void ReportUndefinedSteps()
        {
            _feature.ReportUndefinedSteps();
        }

        [Test]
        public void Adding_two_numbers()
        {
            _feature.Scenarios["Adding two numbers"].Verify();
        }

        [Test]
        public void Subtracting_two_numbers()
        {
            _feature.Scenarios["Subtracting two numbers"].Verify();
        }

        [Test]
        public void Dividing_two_numbers()
        {
            _feature.Scenarios["Dividing two numbers"].Verify();
        }
    }
}
