// This code was generated by the BehaveN tool.

using BehaveN;
using NUnit.Framework;
using System.Reflection;

namespace BehaveN.Examples
{
    [TestFixture]
    public partial class WatiNScenarios
    {
        private Feature _feature = new Feature();

        [TestFixtureSetUp]
        public void LoadScenarios()
        {
            _feature.StepDefinitions.UseStepDefinitionsFromAssembly(GetType().Assembly);
            _feature.ReadEmbeddedResource(GetType().Assembly, "WatiNScenarios.txt");
        }

        [TestFixtureTearDown]
        public void ReportUndefinedSteps()
        {
            _feature.ReportUndefinedSteps();
        }

        [Test]
        public void The_BehaveN_project_is_on_Googles_first_results_page_for_behaven()
        {
            _feature.Scenarios["The BehaveN project is on Google's first results page for \"behaven\""].Verify();
        }
    }
}
